name: taski
description: "To-Do app for the WL-Consultings technical test"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  flutter_gen_runner: ^5.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist/static/Urbanist-Regular.ttf
        - asset: assets/fonts/Urbanist/static/Urbanist-Italic.ttf
          style: italic
        - asset: assets/fonts/Urbanist/static/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/Urbanist/static/Urbanist-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Urbanist/static/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Urbanist/static/Urbanist-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/Urbanist/static/Urbanist-Bold.ttf
          weight: 700
        - asset: assets/fonts/Urbanist/static/Urbanist-BoldItalic.ttf
          style: italic
          weight: 700
